### ISSUE TITLE
always report "clang: error: linker command failed with exit code 1 (use -v to see invocation)" during build

### ISSUE THREAD

**Issue by samye1976** [nevyn/CoreDragon#8] opened 2016-02-14 14:15 UTC
after pod install, I open the DragonFrame and DragonPhotos project in the XCODE 7, then build failed, the error is as following: 

duplicate symbol _OBJC_IVAR_$_AsyncSocket.theContext in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncWritePacket.timeout in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.timeout in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.startOffset in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_CLASS_$_AsyncSocket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_METACLASS_$_AsyncSocket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_CLASS_$_AsyncSpecialPacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_METACLASS_$_AsyncSpecialPacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_CLASS_$_AsyncWritePacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_METACLASS_$_AsyncWritePacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_CLASS_$_AsyncReadPacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_METACLASS_$_AsyncReadPacket in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSpecialPacket.tlsSettings in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theFlags in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theRunLoopModes in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.bufferOwner in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theConnectTimer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theWriteTimer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theReadTimer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncWritePacket.buffer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.buffer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.partialReadBuffer in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theRunLoop in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _AsyncSocketException in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _AsyncSocketErrorDomain in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.term in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theWriteStream in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theReadStream in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.maxLength in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.originalBufferLength in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.readLength in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncWritePacket.tag in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.tag in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theWriteQueue in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theReadQueue in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theCurrentWrite in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theDelegate in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncWritePacket.bytesDone in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncReadPacket.bytesDone in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theCurrentRead in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theUserData in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theNativeSocket6 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theSocket6 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theSource6 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theNativeSocket4 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theSocket4 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
duplicate symbol _OBJC_IVAR_$_AsyncSocket.theSource4 in:
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCerfing.a(AsyncSocket.o)
    /Users/samye/Library/Developer/Xcode/DerivedData/DragonPhotos-hjhzmyhvtsyagxfeorhhsjmjhxig/Build/Products/Debug-iphoneos/libCocoaAsyncSocket.a(AsyncSocket.o)
ld: 47 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by olutsenko** [comment] 2016-02-18 09:49
I have the same problem.

**Comment by olutsenko** [comment] 2016-02-18 16:36
'Cerfing' pod contains duplicate of AsyncSocket.h.

Quick and dirty workaround is to delete it from Pods sources.

![screen shot 2016-02-18 at 14 01 25](https://cloud.githubusercontent.com/assets/303121/13150430/0b8cc36c-d666-11e5-8df8-461b2dde43c7.png)

**Comment by nevyn** [comment] 2016-02-24 17:17
This is due to a change in Cerfing recently, my apologies! Will update as soon as I can. Thanks for the report!

**Comment by nevyn** [comment] 2016-03-30 05:26
I have pushed a new release of Cerfing which fixes this problem. Thanks for the bug report, and thanks for your patience, @samye1976!

**Closed as completed** 2016-03-30 05:26 UTC
Labels: P1
